### ISSUE TITLE
Build Pipeliner pull requests in Software Factory build environment

### ISSUE THREAD

**Issue by sofiia-kalinina** [Daimler/pipeliner#6]
## Background

Merge requests to pipeliner need to be checked in CI tool. As a first step we can use SoftwareFactory.

## Task description

From Software Factory point of view the best way to test pipeliner changes is to use it for Software Factory builds.

* [ ] Resolve dependencies: in Software Factory all references to pipeliner should refer to https://github.com/Daimler/pipeliner.git.
* [ ] Set up a Jenkins job in Software Factory to build pull requests to pipeliner.
* [ ] Manage to have build results visible on GitHub.

## Acceptance criteria

Pull requests made for pipeliner trigger Software Factory Jenkins build. Build status is visible on Github. 

Acting on Behalf of MBition GmbH

https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

**Comment by rpannek** [comment]
Looks good to me!

**Comment by RomelTorres** [comment]
Should the jobs here run internally? Or somewhere on the wild? If we expect contributions from external people. They should be able to have a look a test results.

**Comment by toscalix** [comment]
They should, since we cannot at this point install the tooling required to do it in the open. For now, we will use the repos as single source of truth but we cannot make a standard Open Source project out of it without the rest of the tooling required.
