### ISSUE TITLE
Perform first pull request to Pipeliner

### ISSUE THREAD

**Issue by sofiia-kalinina** [Daimler/pipeliner#7]
## Background

Pipeliner source code should be updated with changes introduced in Software Factory.

## Task description

* [x] Define change scope.
* [x] Push pull request.
* [x] Make sure that the pull request is buildable and meet all criterias, so it can be approved.
* [x] Merge.

## Acceptance criteria

Pull request with source code delta from Software Factory is merged.

Acting on Behalf of MBition GmbH

https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md

**Comment by rpannek** [comment]
Looks good to me too :)
